import fs from "fs-extra";
import path from "path";

/**
 * Smart merge: copy source files into target, preserving existing user files.
 * Only overwrites files that came from AGENT-FORGE (detected by marker comment).
 */
export async function mergeIntoExisting(
  sourceDir: string,
  targetDir: string,
  options: { force?: boolean } = {},
): Promise<{ copied: string[]; skipped: string[]; merged: string[] }> {
  const copied: string[] = [];
  const skipped: string[] = [];
  const merged: string[] = [];

  await walkAndMerge(sourceDir, targetDir, "", copied, skipped, merged, options.force ?? false);

  return { copied, skipped, merged };
}

async function walkAndMerge(
  sourceBase: string,
  targetBase: string,
  relativePath: string,
  copied: string[],
  skipped: string[],
  merged: string[],
  force: boolean,
): Promise<void> {
  const sourceDir = path.join(sourceBase, relativePath);
  const targetDir = path.join(targetBase, relativePath);

  await fs.ensureDir(targetDir);

  const entries = await fs.readdir(sourceDir, { withFileTypes: true });

  for (const entry of entries) {
    const relPath = path.join(relativePath, entry.name);
    const sourcePath = path.join(sourceBase, relPath);
    const targetPath = path.join(targetBase, relPath);

    if (entry.isDirectory()) {
      await walkAndMerge(
        sourceBase,
        targetBase,
        relPath,
        copied,
        skipped,
        merged,
        force,
      );
    } else {
      const targetExists = await fs.pathExists(targetPath);

      if (!targetExists) {
        // File doesn't exist in target — copy it
        await fs.copy(sourcePath, targetPath);
        copied.push(relPath);
      } else if (force) {
        // Force mode — overwrite
        await fs.copy(sourcePath, targetPath);
        merged.push(relPath);
      } else if (await isAgentForgeManaged(targetPath)) {
        // File was generated by AGENT-FORGE — safe to overwrite
        await fs.copy(sourcePath, targetPath);
        merged.push(relPath);
      } else {
        // User-created file — skip
        skipped.push(relPath);
      }
    }
  }
}

/**
 * Check if a file contains the AGENT-FORGE marker comment.
 */
async function isAgentForgeManaged(filePath: string): Promise<boolean> {
  try {
    const content = await fs.readFile(filePath, "utf-8");
    return content.includes("<!-- Generated by AGENT-FORGE -->") || content.includes("<!-- Generated by SpecForge -->");
  } catch {
    return false;
  }
}
